export enum ModelCategories {
  Linear = 'Linear',
  Conv = 'Convolution',
  Pool = 'Pooling',
  Dropout = 'Dropout',
  Regularization = 'Regularization',
  Reshape = 'Reshaping',
  Activation = 'Activation Functions',
  Custom = 'Custom',
  Operations = 'Operations',
  IO = 'I/O',
  Transformer = 'Transformer',
  NonLinearActivation = 'Non-Linear Activation'
}

export enum ModelNodes {
  Conv1d = 'Conv1d',
  Conv2d = 'Conv2d',
  Conv3d = 'Conv3d',
  ConvTranspose1d = 'ConvTranspose1d',
  ConvTranspose2d = 'ConvTranspose2d',
  ConvTranspose3d = 'ConvTranspose3d',
  MaxPool1d = 'MaxPool1d',
  MaxPool2d = 'MaxPool2d',
  MaxPool3d = 'MaxPool3d',
  Dropout = 'Dropout',
  Dropout2d = 'Dropout2d',
  Dropout3d = 'Dropout3d',
  Relu = 'Relu',
  Softmax = 'Softmax',
  Flatten = 'Flatten',
  Concat = 'Concat',
  InModel = 'InModel',
  OutModel = 'OutModel',
  Bilinear = 'Bilinear',
  Linear = 'Linear',
  Softmin = 'Softmin',
  Transformer = 'Transformer',
}
